### ISSUE TITLE
TAPI security mechanism

### ISSUE THREAD

**Issue by rvilalta** [OpenNetworkingFoundation/TAPI#140]
Received:
While trying connect TAPI controller, I bumped into authentication issues.
I see no reference to security in the SWAGGER files, meaning each vendor can implement its own security mechanism. Shouldn’t TAPI take care of its security by token exchange for example?

**Comment by rvilalta** [comment]
Agree that TAPI should care. I will open an issue for this topic. Here is some useful discussion.

http://stackoverflow.com/questions/319530/restful-authentication

In my opinion for this HTTP basic auth over HTTPS might be implemented.

**Comment by italobusi** [comment]
Should this information be part of the T-API Developers Guide?

As far as I have understood, there are multiple ways to implement a T-API  wire protocol and therefore there will be multiple ways to secure the communication channel.

I think this is yet another aspects, among others described in the T-API Development Guide, the T-API client and server sides need to agree upon in order to communicate.

**Comment by rvilalta** [comment]
Exactly.

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
