### ISSUE TITLE
TAPI RPCs for the ConnectivityService and other modules should be consistent with the CRUD flavors in the TAPI config tree

### ISSUE THREAD

**Issue by karthik-sethuraman** [OpenNetworkingFoundation/TAPI#196]
Many parameters which are configurable in the REST/CRUD style of the RESTConf mapping are not not present in the RPCs. For example, the following parameters are missing in the ConnectivityService Create/Update RPC - servicePort, state, direction, name, etc

**Comment by arthurMll** [comment]
It seems this issue has not been properly addressed in latest TAPI release.
Currently, the defined RPCs are not augmented with the technology specific models such tapi-photonic-media.yang or tapi-odu.yang

This is a critical issue for implementations based on Operations API flavor.

I highly recommend to assess this issue asap in order to get it fixed in the next release.

**Comment by arthurMll** [comment]
Shall we open a new issue? To push it higher in the issue's list?

**Comment by karthik-sethuraman** [comment]
No... this is sufficient - we will plan to do a bug-fix release for 2.1. The longer decision on whether to support duplicate RPCs (v/s actions) for CRUD operations is TBD.
