### ISSUE TITLE
Ambiguity in the response schema for the same API across different swagger files

### ISSUE THREAD

**Issue by ganeshrnayak** [OpenNetworkingFoundation/TAPI#365]
There is an ambiguity in the response schema for the same API across different swagger(OAS/*.yaml) files.

For the same URL, there are different response schema published the in the swagger files :

ex : for the same API 
/data/context/topology={uuid}/node={node-uuid}/owned-node-edge-point={owned-node-edge-point-uuid}/ 
tapi-topology@2018-08-31.yaml has the response schema : 
$ref: "#/definitions/tapi.topology.NodeEdgePoint"

However, tapi-connectivity@2018-08-31.yaml has the response schema : 
$ref: "#/definitions/tapi.topology.node.OwnedNodeEdgePoint"

There are a few more such ambiguities observed, can be seen in the attached files :
![photonic-conectivity-service_vs_connectivity-connectivity-service](https://user-images.githubusercontent.com/36321910/46518136-6f1fc900-c890-11e8-9f9b-d67e1fac87d9.png)
![topology-owned-nep_vs_connectivity-owned-nep](https://user-images.githubusercontent.com/36321910/46518138-6f1fc900-c890-11e8-9ea5-7f7d4e8f5c33.png)
![connectivity-cep_vs_photonic-cep](https://user-images.githubusercontent.com/36321910/46518139-6fb85f80-c890-11e8-8210-d6db76f39d21.png)
![connectivity-sip_vs_photonic-sip](https://user-images.githubusercontent.com/36321910/46518141-6fb85f80-c890-11e8-8ca5-9b9ab9e655a0.png)

cc : @amazzini

**Comment by bartoszm** [comment]
@ganeshrnayak  could you please give me some insights on how do you generate the swagger?
e.g. is it always generated from the same set of yang files? how to reproduce what you do observe

**Comment by pedrofsamaral** [comment]
Hello,

this seems to happen because the OAS files are generated individually, meaning that for the example the connectivity model augments the node/**_owned-node-edge-point_** with the **_cep-list_** resulting that on a different (extended) object in connectivity OAS to address the difference to the "base" node-edge-point.
I would say that the individual OAS files are still relevant and useful for who wants to implement only a single service (e.g. only topology) but I would consider to generate also a OAS with all the services in it.

Maybe the way to go for the example would be to use only connectivity OAS since it imports and extends topology model. This should apply to all extensions, i.e. to use as reference the OAS of the model that extends and includes the "base" one.
The only issue with this, and that's why I suggest to have a "total" OAS with all models is for the case where two models extend the same one with different things and we need to have as reference both OAS.

I hope this clarifies the issue reported.

Also, it would be helpful as guidance to have the exact command that was used to generate the published OAS files from the published YANG for the ones that want to generate their own combinations of T-API models on a single OAS.

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
